### ISSUE TITLE
Contributing to episode 01-introduction

### ISSUE THREAD

**Issue by csoneson** [carpentries-incubator/bioc-rnaseq#21]
## Tasks
- [x] Shortest Introduction to RNA-seq analysis (and why Bioconductor) @mblue9 
- [ ] show example figure
- [ ] explanation of the experiment 
               https://pubmed.ncbi.nlm.nih.gov/28696309/

**Comment by csoneson** [comment]
Closing as outdated - the experimental data is explained in a later episode
